version: '3'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: wallapop_salva
    volumes:
      - ./mongo/dump/wallapop_salva:/dump
      - ./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh
    networks:
      - app
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - mongo_db
    restart: always
    ports:
      - "3000:3000"
    command: 'npm run start'
    networks:
      - app
  frontend:
    build: ./frontend
    container_name: frontend_container
    depends_on:
      - backend
    restart: always
    ports:
      - 4200:4200
    networks:
      - app
networks:
  app: