version: '3'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/dump/wallapop_salva:/dump
      - ./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh
    networks:
      - practica_net
  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - mongo_db
    restart: always
    ports:
      - "3000:3000"
    command: 'npm run start'
    networks:
      - practica_net
  frontend:
    build: ./frontend
    container_name: frontend_container
    depends_on:
      - backend
    restart: always
    ports:
      - 4200:4200
    networks:
      - practica_net
  mongo_express:
    image: mongo-express:latest
    container_name: adminMongo_container
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    env_file:
      - variables.env
    networks:
      - practica_net
  loadBalancer:
    image: nginx:latest
    restart: always
    container_name: loadBalancer_container
    ports:
      - "8080:80"
    volumes:
      - "./loadbalancer/nginx.conf:/etc/nginx/nginx.conf"
    command: nginx -g "daemon off;"
    networks:
      - practica_net
networks:
  practica_net: