#STAGE 1
FROM node:19-alpine as installer
WORKDIR /app
COPY ./package.json ./package.json
RUN ["npm", "install"]

#STAGE 2
FROM node:19-alpine
WORKDIR /app
RUN apk update && apk add bash
COPY ./package.json ./package.json
COPY ./app ./app
COPY ./server.js ./server.js
COPY ./.env ./.env
COPY --from=installer /app/node_modules ./node_modules
EXPOSE 3000